### ISSUE TITLE
`grep: invalid option -- P` error on Mac

### ISSUE THREAD

**Issue by JackPGreen** [hazelcast/backport#7]
[`grep` on Mac no longer supports the `--perl-regexp` option](https://stackoverflow.com/q/16658333).

```
+ COMMIT_MSG='Fix private test repository access [DI-236] (#221)'
++ echo 'Fix private test repository access [DI-236] (#221)'
++ grep -oP '#(\d+)'
++ tail -n1
++ cut -c2-
grep: invalid option -- P
usage: grep [-abcdDEFGHhIiJLlMmnOopqRSsUVvwXxZz] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
```

[DI-236]: https://hazelcast.atlassian.net/browse/DI-236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DI-236]: https://hazelcast.atlassian.net/browse/DI-236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ldziedziul** [comment]
Could you try if `grep -Eo '#[0-9]+'` does the job?

**Comment by JackPGreen** [comment]
> Could you try if `grep -Eo '#[0-9]+'` does the job?

That works, but I'm guessing there was a reason it was changed from that in aaeacd087957fa4cbbea85dd1fec6e6633d89576

**Comment by ldziedziul** [comment]
Because the `-Eo #(\d+)`  doesn't work with mac (non-gnu) grep. `-Eo '#[0-9]+'` is a different regex
